name: movie_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  floor: any
  retrofit: ^4.0.1
  cached_network_image: ^3.2.0
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  floor_generator: 1.4.2
  build_runner: ^2.4.6
  analyzer: ^5.0.0


flutter:
  uses-material-design: true